import random
import MySQLdb

db = MySQLdb.connect(user="childcount",passwd="childcount",db="childcount")
c = db.cursor()

last_names = ["Smith", "Johnson", "Williams", "Jones", "Brown",
              "Davis", "Miller", "Wilson", "Moore", "Taylor",
              "Anderson", "Thomas", "Jackson", "White", "Harris",
              "Martin", "Thompson", "Garcia", "Martinez", "Robinson",
              "Clark", "Rodriguez", "Lewis", "Lee", "Walker", "Hall",
              "Allen", "Young", "Hernandez", "King", "Wright",
              "Lopez", "Hill", "Scott", "Green", "Adams", "Baker",
              "Gonzalez", "Nelson", "Carter", "Mitchell", "Perez",
              "Roberts", "Turner", "Phillips", "Campbell", "Parker",
              "Evans", "Edwards", "Collins", "Stewart", "Sanchez",
              "Morris", "Rogers", "Reed", "Cook", "Morgan", "Bell",
              "Murphy", "Bailey", "Rivera", "Cooper", "Richardson",
              "Cox", "Howard", "Ward", "Torres", "Peterson", "Gray",
              "Ramirez", "James", "Watson", "Brooks", "Kelly",
              "Sanders", "Price", "Bennett", "Wood", "Barnes", "Ross",
              "Henderson", "Coleman", "Jenkins", "Perry", "Powell",
              "Long", "Patterson", "Hughes", "Flores", "Washington",
              "Butler", "Simmons", "Foster", "Gonzales", "Bryant",
              "Alexander", "Russell", "Griffin", "Diaz", "Hayes",
              "Myers", "Ford", "Hamilton", "Graham", "Sullivan",
              "Wallace", "Woods", "Cole", "West", "Jordan", "Owens",
              "Reynolds", "Fisher", "Ellis", "Harrison", "Gibson",
              "Mcdonald", "Cruz", "Marshall", "Ortiz", "Gomez",
              "Murray", "Freeman", "Wells", "Webb", "Simpson",
              "Stevens", "Tucker", "Porter", "Hunter", "Hicks",
              "Crawford", "Henry", "Boyd", "Mason", "Morales",
              "Kennedy", "Warren", "Dixon", "Ramos", "Reyes", "Burns",
              "Gordon", "Shaw", "Holmes", "Rice", "Robertson", "Hunt",
              "Black", "Daniels", "Palmer", "Mills", "Nichols",
              "Grant", "Knight", "Ferguson", "Rose", "Stone",
              "Hawkins", "Dunn", "Perkins", "Hudson", "Spencer",
              "Gardner", "Stephens", "Payne", "Pierce", "Berry",
              "Matthews", "Arnold", "Wagner", "Willis", "Ray",
              "Watkins", "Olson", "Carroll", "Duncan", "Snyder",
              "Hart", "Cunningham", "Bradley", "Lane", "Andrews",
              "Ruiz", "Harper", "Fox", "Riley", "Armstrong",
              "Carpenter", "Weaver", "Greene", "Lawrence", "Elliott",
              "Chavez", "Sims", "Austin", "Peters", "Kelley",
              "Franklin", "Lawson", "Fields", "Gutierrez", "Ryan",
              "Schmidt", "Carr", "Vasquez", "Castillo", "Wheeler",
              "Chapman", "Oliver", "Montgomery", "Richards",
              "Williamson", "Johnston", "Banks", "Meyer", "Bishop",
              "Mccoy", "Howell", "Alvarez", "Morrison", "Hansen",
              "Fernandez", "Garza", "Harvey", "Little", "Burton",
              "Stanley", "Nguyen", "George", "Jacobs", "Reid", "Kim",
              "Fuller", "Lynch", "Dean", "Gilbert", "Garrett",
              "Romero", "Welch", "Larson", "Frazier", "Burke",
              "Hanson", "Day", "Mendoza", "Moreno", "Bowman",
              "Medina", "Fowler", "Brewer", "Hoffman", "Carlson",
              "Silva", "Pearson", "Holland", "Douglas", "Fleming",
              "Jensen", "Vargas", "Byrd", "Davidson", "Hopkins",
              "May", "Terry", "Herrera", "Wade", "Soto", "Walters",
              "Curtis", "Neal", "Caldwell", "Lowe", "Jennings",
              "Barnett", "Graves", "Jimenez", "Horton", "Shelton",
              "Barrett", "Obrien", "Castro", "Sutton", "Gregory",
              "Mckinney", "Lucas", "Miles", "Craig", "Rodriquez",
              "Chambers", "Holt", "Lambert", "Fletcher", "Watts",
              "Bates", "Hale", "Rhodes", "Pena", "Beck", "Newman", ]

male_names = ["Jacob", "Michael", "Joshua", "Matthew", "Ethan",
              "Andrew", "Daniel", "William", "Joseph", "Christopher",
              "Anthony", "Ryan", "Nicholas", "David", "Alexander",
              "Tyler", "James", "John", "Dylan", "Nathan", "Jonathan",
              "Brandon", "Samuel", "Christian", "Benjamin", "Zachary",
              "Logan", "Jose", "Noah", "Justin", "Elijah", "Gabriel",
              "Caleb", "Kevin", "Austin", "Robert", "Thomas",
              "Connor", "Evan", "Aidan", "Jack", "Luke", "Jordan",
              "Angel", "Isaiah", "Isaac", "Jason", "Jackson",
              "Hunter", "Cameron", "Gavin", "Mason", "Aaron", "Juan",
              "Kyle", "Charles", "Luis", "Adam", "Brian", "Aiden",
              "Eric", "Jayden", "Alex", "Bryan", "Sean", "Owen",
              "Lucas", "Nathaniel", "Ian", "Jesus", "Carlos",
              "Adrian", "Diego", "Julian", "Cole", "Ashton", "Steven",
              "Jeremiah", "Timothy", "Chase", "Devin", "Seth",
              "Jaden", "Colin", "Cody", "Landon", "Carter", "Hayden",
              "Xavier", "Wyatt", "Dominic", "Richard", "Antonio",
              "Jesse", "Blake", "Sebastian", "Miguel", "Jake",
              "Alejandro", "Patrick", "Carson", "Victor", "Alexis",
              "Caden", "Kaden", "Riley", "Brayden", "Bryce", "Trevor",
              "Henry", "Jeremy", "Liam", "Mark", "Garrett", "Marcus",
              "Tristan", "Ivan", "Kaleb", "Vincent", "Jorge",
              "Kenneth", "Brady", "Oscar", "Tanner", "Joel",
              "Eduardo", "Jared", "Paul", "Edward", "Collin", "Alan",
              "Parker", "Cooper", "Conner", "Colton", "Maxwell",
              "Dakota", "Nicolas", "Cristian", "Stephen", "Grant",
              "Peter", "Ricardo", "Josiah", "Gage", "Brendan", "Omar",
              "George", "Jeffrey", "Francisco", "Spencer", "Preston",
              "Braden", "Fernando", "Derek", "Levi", "Cesar",
              "Javier", "Damian", "Eli", "Peyton", "Nolan", "Micah",
              "Max", "Travis", "Dalton", "Shane", "Manuel", "Andres",
              "Edgar", "Shawn", "Erik", "Edwin", "Emmanuel", "Devon",
              "Bradley", "Jonah", "Mario", "Erick", "Malachi", "Ty",
              "Ayden", "Johnathan", "Wesley", "Colby", "Trenton",
              "Donovan", "Raymond", "Giovanni", "Jalen", "Hector",
              "Marco", "Abraham", "Gregory", "Leonardo", "Dillon",
              "Damien", "Clayton", "Bryson", "Andre", "Sergio",
              "Roberto", "Martin", "Jaylen", "Andy", "Dawson",
              "Elias", "Josue", "Brody", "Harrison", "Drew", "Corey",
              "Mitchell", "Scott", "Israel", "Taylor", "Ruben",
              "Dominick", "Braxton", "Calvin", "Miles", "Brett",
              "Dustin", "Rafael", "Pedro", "Avery", "Troy", "Jace",
              "Oliver", "Frank", "Zane", "Camden", "Ronald", "Jakob",
              "Gerardo", "Skyler", "Payton", "Trey", "Roman",
              "Armando", "Griffin", "Raul", "Malik", "Marcos",
              "Brock", "Alec", "Derrick", "Kai", "Phillip", "Keith",
              "Cade", "Chance", "Johnny", "Enrique", "Keegan",
              "Simon", "Allen", "Trent", "Xander", "Casey", "Jaiden",
              "Drake", "Cayden", "Donald", "Leo", "Jaxon", "Fabian",
              "Corbin", "Julio", "Angelo", "Dante", "Jaime",
              "Grayson", "Kyler", "Lance", "Kameron", "Brenden",
              "Zander", "Emanuel", "Jimmy", "Landen", "Alberto",
              "Tyson", "Chandler", "Darius", "Tucker", "Adan",
              "Zackary", "Gustavo", "Saul", "Santiago", "Mathew",
              "Jerry", "Lukas", "Myles", "Lane", "Lorenzo",
              "Nickolas", "Brennan", "Emilio", ]

female_names = ["Emily", "Emma", "Madison", "Olivia", "Hannah",
                "Abigail", "Isabella", "Ashley", "Samantha",
                "Elizabeth", "Alexis", "Sarah", "Grace", "Alyssa",
                "Sophia", "Lauren", "Brianna", "Kayla", "Natalie",
                "Anna", "Jessica", "Taylor", "Chloe", "Hailey", "Ava",
                "Jasmine", "Sydney", "Victoria", "Ella", "Mia",
                "Morgan", "Julia", "Kaitlyn", "Rachel", "Katherine",
                "Megan", "Alexandra", "Jennifer", "Destiny",
                "Allison", "Savannah", "Haley", "Mackenzie", "Brooke",
                "Maria", "Nicole", "Makayla", "Trinity", "Kylie",
                "Kaylee", "Paige", "Lily", "Faith", "Zoe",
                "Stephanie", "Jenna", "Andrea", "Riley", "Katelyn",
                "Angelina", "Kimberly", "Madeline", "Mary", "Leah",
                "Lillian", "Michelle", "Amanda", "Sara", "Sofia",
                "Jordan", "Alexa", "Rebecca", "Gabrielle", "Caroline",
                "Vanessa", "Gabriella", "Avery", "Marissa", "Ariana",
                "Audrey", "Jada", "Autumn", "Evelyn", "Jocelyn",
                "Maya", "Arianna", "Isabel", "Amber", "Melanie",
                "Diana", "Danielle", "Sierra", "Leslie", "Aaliyah",
                "Erin", "Amelia", "Molly", "Claire", "Bailey",
                "Melissa", "Brooklyn", "Katie", "Nevaeh", "Catherine",
                "Angela", "Amy", "Isabelle", "Jacqueline", "Jade",
                "Gabriela", "Madelyn", "Shelby", "Mariah", "Gracie",
                "Kennedy", "Mya", "Breanna", "Daniela", "Adriana",
                "Briana", "Courtney", "Kathryn", "Christina",
                "Gianna", "Alexandria", "Lydia", "Miranda", "Angel",
                "Laura", "Alicia", "Ashlyn", "Alexia", "Margaret",
                "Peyton", "Rylee", "Sophie", "Kendall", "Kelly",
                "Summer", "Ana", "Kylee", "Reagan", "Natalia",
                "Daisy", "Lindsey", "Naomi", "Kate", "Kelsey",
                "Sabrina", "Alondra", "Jillian", "Cheyenne",
                "Mckenzie", "Karen", "Skylar", "Paris", "Mikayla",
                "Ruby", "Payton", "Addison", "Caitlin", "Kyla",
                "Juliana", "Caitlyn", "Abby", "Crystal", "Layla",
                "Cassidy", "Delaney", "Bianca", "Mariana",
                "Charlotte", "Cassandra", "Tiffany", "Valeria",
                "Angelica", "Carly", "Alana", "Valerie", "Jasmin",
                "Hope", "Giselle", "Erica", "Jazmin", "Genesis",
                "Jordyn", "Mallory", "Kiara", "Ellie", "Aubrey",
                "Serenity", "Erika", "Veronica", "Chelsea", "Karla",
                "Karina", "Sadie", "Eva", "Jamie", "Julianna",
                "Brenda", "Mckenna", "Celeste", "Lucy", "Alejandra",
                "Maggie", "Zoey", "Amaya", "Esmeralda", "Adrianna",
                "Bethany", "Makenzie", "Lilly", "Elena", "Nadia",
                "Jayla", "Meghan", "Cadence", "Kyra", "Ariel",
                "Aliyah", "Cynthia", "Camryn", "Liliana", "Elise",
                "Monica", "Makenna", "Kailey", "Alison", "Lizbeth",
                "Hanna", "Vivian", "Macy", "Jayden", "Desiree",
                "Haylee", "Rebekah", "Allyson", "Carmen", "Brittany",
                "Lindsay", "Josephine", "Nina", "Hayley", "Heather",
                "Jazmine", "Asia", "Laila", "Jaden", "Camille",
                "Kara", "Cameron", "Katelynn", "Carolina", "Joanna",
                "Shannon", "Selena", "Keira", "Aniya", "Bella",
                "Julie", "Reese", "Raven", "Kristen", "Piper",
                "Guadalupe", "Heaven", "Diamond", "Kendra", "Savanna",
                "Claudia", "Fatima", "Alaina", "Kira", "Dakota",
                "Cecilia", "Tessa", "April", "Miriam", "Sandra",
                "Katrina", "Kayleigh", "Ashlee", "Michaela", "Clara",
                "Anastasia", "Camila", "Ashlynn", "Nancy", "Tatiana",
                "Stella", "Jadyn", "Holly", "Aniyah", "Kaitlin",
                "Allie", "Kirsten", "Kamryn", "Annabelle", "Natasha",]

names = []

for l in last_names:
    for m in male_names:
        names.append( (m,l) )
    for f in female_names:
        names.append( (f,l) )

c.execute("SELECT id FROM cc_patient")
ids = c.fetchall()
for id in ids:
    i = random.randrange(len(names))
    f, l = names.pop(i)
    command = "UPDATE cc_patient SET first_name = '%(f)s', last_name = '%(l)s' WHERE id = %(id)s" % {"f" : f, "l" : l, "id" : id[0]}
    # print command
    c.execute(command)
