#!/bin/bash
# vim: ai ts=4 sts=4 et sw=4 encoding=utf-8
# maintainer: katembu

USB_ROOT="/Volumes/usb-backup/"
BACKUP_DIR="vms_backup"

NOW=$(date +"%m_%d_%Y")

DIRECTORY="$USB_ROOT$BACKUP_DIR"

#Get a Directory|Location to save Image. 
#If it doesnot exist exit or use default
LOCATION="$2"
echo "checking if location exists: $LOCATION"
if [ -d $location ]; 
then
	echo "Location exists"
	DIRECTORY="$LOCATION"
else 
    echo "Location doesnot exist. Trying to create one"
	if [ mkdir $DIRECTORY ];
	then 
	    echo "Successfully created file location"
	else
	    echo "Unable to create file location. Exiting"
	    exit 1
	fi  
fi 


backup_omrs_vm()
{

    #Clone Name
    name="$DIRECTORY/omrs_$NOW.ovf"

    #STOP
    echo "Stop OMRS VM for cloning "
    VBoxManage controlvm omrs acpipowerbutton

    #Export image to specified Disk
    #CHECK IF SIMILAR IMAGE ALREADY EXIST
    if [ -f $name ]; 
    then
	    echo "Similar Clone already exists"
    else 
        echo "Creating OMRS  Backup clone "
	    VBoxManage export omrs -o $name

    fi 
    
    #restart - To add head or headless
    echo "Restarting OMRS-VM "
    VBoxManage startvm omrs --type headless
}

backup_rsms_vm()
{
    #Clone Name
    name="$DIRECTORY/rsms_$NOW.ovf"

    #STOP
    echo "Stop RSMS VM for cloning "
    VBoxManage controlvm rsms acpipowerbutton

    #Export image to specified Disk
    #CHECK IF SIMILAR IMAGE ALREADY EXIST
    if [ -f $name ]; 
    then
	    echo "Similar Clone already exists"
    else 
        echo "Creating RSMS backup clone"
	    VBoxManage export rsms -o $name

    fi 

    #restart - To add head or headless
    echo "Restarting RSMS-VM "
    VBoxManage startvm rsms --type headless


}


case "$1" in
    omrs)
	    echo "Backup OMRS virtual machines"
        backup_omrs_vm
        ;;
    
    rsms)
	    echo "Backup RSMS virtual machines"
        backup_rsms_vm
        ;;
    
    all)
	    echo "Backup both RSMS and OMRS virtual machines"
	    backup_omrs_vm
        backup_rsms_vm
	;;
    *)
        echo "Usage: {rsms|omrs|all} filelocation" >&2
        exit 1
        ;;
esac

