#!/bin/bash
# vim: ai ts=4 sts=4 et sw=4 encoding=utf-8
# maintainer: katembu

NOW=$(date +"%m_%d_%Y")

#Get a Directory|Location to save Image. 
#If it doesnot exist exit or use default

DIRECTORY="$2"

if [ -z $DIRECTORY ]
then
    echo "Usage: {rsms|omrs|all} filelocation"
    echo "Specify export location "
    exit 1
else 
	if [ ! -d $DIRECTORY ];
	then
	    echo "Location doesnot exist. Exiting"
	    exit 1
	fi  
fi 


backup_omrs_vm()
{

    #Clone Name
    VIMAGE="$1"
    name="$DIRECTORY$VIMAGE-$NOW.ovf"

    #STOP
    echo "Stop $VIMAGE VM for cloning "
    VBoxManage controlvm omrs acpipowerbutton
    sleep 90

    #Export image to specified Disk
    #CHECK IF SIMILAR IMAGE ALREADY EXIST
    if [ -f $name ]; 
    then
	    echo "Similar Clone already exists"
    else 
        echo "Creating $VIMAGE  Backup clone "
	    VBoxManage export $VIMAGE -o $name

    fi 
    
    #restart - To add head or headless
    echo "Restarting $VIMAGE-VM "
    VBoxManage startvm $VIMAGE --type headless
}

backup_rsms_vm()
{
    #Clone Name
    VIMAGE="$1"
    name="$DIRECTORY$VIMAGE-$NOW.ovf"

    #STOP
    echo "Stop $VIMAGE VM for cloning "
    VBoxManage controlvm rsms acpipowerbutton
    sleep 90

    #Export image to specified Disk
    #CHECK IF SIMILAR IMAGE ALREADY EXIST
    if [ -f $name ]; 
    then
	    echo "Similar Clone already exists"
    else 
        echo "Creating $VIMAGE backup clone"
	    VBoxManage export $VIMAGE -o $name

    fi 

    #restart - To add head or headless
    echo "Restarting $VIMAGE-VM "
    VBoxManage startvm $VIMAGE --type headless


}


case "$1" in
    omrs)
	    echo "Backup $1 virtual machines"
        backup_omrs_vm $1
        ;;
    
    rsms)
	    echo "Backup $1 virtual machines"
        backup_rsms_vm $1
        ;;
    
    all)
	    echo "Backup both RSMS and OMRS virtual machines"
	    backup_omrs_vm "omrs"
        backup_rsms_vm "rsms"
	;;
    *)
        echo "Usage: {rsms|omrs|all} filelocation" >&2
        exit 1
        ;;
esac

